# This is a basic workflow to help you get started with Actions

name: CI Pipeline

on:          
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'version.txt'  
  workflow_dispatch: 

env:
  CONTAINER_REPO: 'birdmodify/birdtest-webapp'
  AZURE_WEBAPP_NAME: bird-webapp-demo-testing 
  
jobs:
  
  set-version-control:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:        
          ref: ${{ github.ref }}  
       
      - run: echo The tags is ${{ github.sha }}
      - run: | 
            var_date=$(date '+%Y%m%d')
            echo var_date=${var_date}
            echo "VERSION_NO=${var_date}-${GITHUB_RUN_NUMBER} " >> $GITHUB_ENV  
      
      - run: echo VERSION_NO=${VERSION_NO}
      - run: echo VERSION_NO=${VERSION_NO} > version.txt
      - run: ls -la
      
      - name: Commit version files
        run: |          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add version.txt
          git commit -m "update version to be ${VERSION_NO}"
          
      - name: Push version changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  

  build-container:    
    runs-on: ubuntu-latest
    needs: [set-version-control]
    environment: testing
      
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:        
            ref: ${{ github.ref }}   
      
      - name: Setup Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'     
     
      - run: echo VERSION_NO=${VERSION_NO}
