# This is a basic workflow to help you get started with Actions

name: CI Pipeline

on:          
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'version.txt'  
  workflow_dispatch: 

env:
  CONTAINER_REPO: 'birdmodify/birdtest-webapp'
  AZURE_WEBAPP_NAME: bird-webapp-demo-testing 
  
jobs:
  
  set-version-control:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:        
          ref: ${{ github.ref }}  
       
      - run: echo The tags is ${{ github.sha }}
      - run: v_date=$(date '+%Y%m%d')
      - run: echo ${v_date}-${GITHUB_RUN_NUMBER} 
      - run: echo GITHUB_JOB=${GITHUB_JOB}
      - run: ls -la
      
      #- name: Commit version files
      #  run: |          
      #    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #    git config --local user.name "github-actions[bot]"
      #    git add version.txt
      #    git commit -m "update version to be ${v_date}-${GITHUB_RUN_NUMBER}"
          
      #- name: Push version changes
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}  
