name: demo01
on:
 # workflow_call:
 #   inputs:
 #     username:
 #       description: 'A username passed from the caller workflow'
 #       default: 'john-doe'
 #       required: false
 #       type: string
        
  workflow_dispatch:        
    inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string     
    
  
jobs: 
  my_job:
    runs-on: ubuntu-latest
    outputs:      
        tag: ${{ github.sha }}
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
       
      - uses: ./.github/action/demo2@master
        with:
          username: birdmodify
