name: demo01
on:          
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: false 
        default: 'birdmodify' 
        type: string  
  
jobs: 
  print-username:
    runs-on: ubuntu-latest
    outputs:      
        tag: ${{ github.sha }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Print the input username to STDOUT
        id: step01
        run: echo The username is ${{ github.event.inputs.username }}
       
      - run: echo The tags is ${{ github.sha }}
      
      - run: echo ${{ github.sha }} > version.txt
      - run: ls -la
      
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
                
      
  call-next-action:
       uses: birdmodify69/gitaction-lab-web/.github/workflows/demo2.yml@master
       with:
         username: ${{ github.event.inputs.username }}
