name: demo01
on:
  #workflow_call:
  #  inputs:
  #    username:
  #      description: 'A username passed from the caller workflow'
  #      default: 'john-doe'
  #      required: false
  #      type: string
        
  #workflow_dispatch:        
  #  inputs:
  #      username:
  #        description: 'A username passed from the caller workflow'
  #        default: 'birdmodify'
  #        required: false
  #        type: string     
          
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: false 
        default: 'birdmodify' 
        type: string  
  
jobs: 
  print-username:
    runs-on: ubuntu-latest
    outputs:      
        tag: ${{ github.sha }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Print the input username to STDOUT
        id: step01
        run: echo The username is ${{ github.event.inputs.username }}
       
      - run: echo The tags is ${{ github.sha }}
      
      #- run: pwd
      #- run: ls -la
      #- run: ls -la .github/workflows/
      #- run: cat /home/runner/work/gitaction-lab-web/gitaction-lab-web/.github/workflows/demo2.yml
      
  call-next-action:
       uses: birdmodify69/gitaction-lab-web/.github/workflows/demo2.yml@master
       with:
         username: ${{ github.event.inputs.username }}
