name: demo02
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    #outputs:
    #  workflow_output1:
    #    description: "The first job output"
    #    value: ${{ jobs.my_job.outputs.job_output1 }}

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
