name: demo02
on:
  #workflow_run:
  #    workflows: [demo01]
  #    types:
  #      - completed
        
  workflow_call:
    inputs:
      username:
        required: true
        type: string
       
    #outputs:
    #  workflow_output1:
    #    description: "The first job output"
    #    value: ${{ jobs.my_job.outputs.job_output1 }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Print the input name to STDOUT
        run: echo The tag is ${{ github.event.inputs.username }}
