name: demo01
on:
  #workflow_call:
  #  inputs:
  #    username:
  #      description: 'A username passed from the caller workflow'
  #      default: 'john-doe'
  #      required: false
  #      type: string
        
  #workflow_dispatch:        
  #  inputs:
  #      username:
  #        description: 'A username passed from the caller workflow'
  #        default: 'birdmodify'
  #        required: false
  #        type: string     
          
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: false 
        default: 'birdmodify' 
        type: string  
  
jobs: 
  print-username:
    runs-on: ubuntu-latest
    outputs:      
        tag: ${{ github.sha }}
        
    steps:
      - name: Print the input tags to STDOUT
        id: step01
        run: echo The tags is ${{ github.event.inputs.username }}
       
      #- uses: ./demo2@master
      #  with:
      #    username: birdmodify
