name: demo01
on:
 # workflow_call:
 #   inputs:
 #     username:
 #       description: 'A username passed from the caller workflow'
 #       default: 'john-doe'
 #       required: false
 #       type: string
        
  workflow_dispatch:        
    inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string     
    
  
jobs: 
  my_job:
    runs-on: ubuntu-latest
    outputs:      
        tag: ${{ github.sha }}
        
    steps:
      - name: Print the input name to STDOUT
        id: test01
        run: echo The username is ${{ inputs.username }}
       
      #- uses: ./demo2@master
      #  with:
      #    username: birdmodify
