name: demo01
on:
 # workflow_call:
 #   inputs:
 #     username:
 #       description: 'A username passed from the caller workflow'
 #       default: 'john-doe'
 #       required: false
 #       type: string
        
  workflow_dispatch:        
    inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string     
    
  
jobs: 
  my_job:
    runs-on: ubuntu-latest
    outputs:      
        tag: ${{ github.sha }}
        
    steps:           
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
       
      - uses: ./.github/workflows/demo2.yml@709020b92239fccb36525a9e7aa2239a8a8772c4
        with:
          username: birdmodify
