name: demo02
on:
  #workflow_run:
  #    workflows: [demo01]
  #    types:
  #      - completed
        
  workflow_call:
    inputs:
      username:
        required: true
        type: string
       
    #outputs:
    #  workflow_output1:
    #    description: "The first job output"
    #    value: ${{ jobs.my_job.outputs.job_output1 }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:        
      - name: Print the input name to STDOUT
        run: echo The tag is ${{ github.event.inputs.username }}

  get-variable:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
        - name: Checkout
          uses: actions/checkout@v2.4.0
        
        - name: Set Version
          run: |
            var_version=$(cat version.txt)
            echo "VERSION_NO=${var_version}" >> $GITHUB_ENV
            #echo '::set-output name=VERSION_NO::${var_version}'
          #id: get-version-id
          
          
        - name: Get Version
          #run: echo "Version is ${{ steps.get-version-id.outputs.VERSION_NO }}"
          run: echo "Version is ${{ env.VERSION_NO }}"
