name: demo01
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
        
  workflow_dispatch:        
    inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string     
    
  
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

  call-workflow-passing-data:
    uses: birdmodify69/gitaction-lab-web/.github/workflows/demo2.yml@main
    with:
      username: mona
 
