name: Deploy to Testing

# Controls when the workflow will run
on:
  workflow_run:
      workflows: [build-container]
      types:
        - completed
  workflow_dispatch:

env:
  CONTAINER_REPO: 'birdmodify/birdtest-webapp'
  AZURE_WEBAPP_NAME: bird-webapp-demo-testing 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy-to-testing:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      #needs: [build-container]
      environment: 
        name: testing
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set Version
        run: |
          var_version=$(cat version.txt)
          echo "VERSION_NO=${var_version}" >> $GITHUB_ENV         

      - name: Get Version         
        run: echo "Version is ${{ env.VERSION_NO }}"
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.webapp }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}        
          images: 'index.docker.io/${{ env.CONTAINER_REPO }}:${{ env.VERSION_NO }}'
