# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run : CI=true npm run test    
    
    - name: Code Coverage Summary
      # You may pin to the exact commit or the version.
      # uses: irongut/CodeCoverageSummary@065eaf7bb520f8e36979631183958be5e7934e31
      uses: irongut/CodeCoverageSummary@v1.1.0
      with:
        # Code coverage file to analyse.
        filename: coverage/cobertura-coverage.xml
        # Include a Line Rate coverage badge in the output using shields.io - true / false (default).
        badge: true # optional, default is false
        # Fail if overall Line Rate below lower threshold - true / false (default).
        fail_below_min: false # optional, default is false
        # Output Format - markdown or text (default).
        format: Cobertura # optional, default is text
        # Include health indicators in the output - true (default) / false.
        indicators: true # optional, default is true
        # Output Type - console (default), file or both.
        output: console # optional, default is console
        
        
    #- run: npm run build --if-present    
