# This is a basic workflow to help you get started with Actions

name: test-notify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  #MS_TEAM_URL: https://gablegrp.webhook.office.com/webhookb2/dd936596-4bd2-496c-8e78-b5bc1ba6fb8f@45be8033-beb7-4d4b-ab77-608ee11e6449/IncomingWebhook/18653518e0d344f5bd0d0492d54bbe77/89ed1696-cd46-4df0-b79f-ac4bc01308b1
  MS_TEAM_URL: https://gablegrp.webhook.office.com/webhookb2/dd936596-4bd2-496c-8e78-b5bc1ba6fb8f@45be8033-beb7-4d4b-ab77-608ee11e6449/IncomingWebhook/9b5330ea8fc04428bc6938a33552c44c/89ed1696-cd46-4df0-b79f-ac4bc01308b1
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:        
            ref: ${{ github.ref }}  
            
      - name: Set Version
        run: |
          var_version=$(cat version.txt)
          echo "VERSION_NO=${var_version}" >> $GITHUB_ENV
          
      - name: Get Version         
        run: echo "Version is ${{ env.VERSION_NO }}"  
      - run: echo "GITHUB_RUN_NUMBER is ${GITHUB_RUN_NUMBER}"  
      - run: echo "Author is ${{ github.event.pusher.name }} "  
          
      - name: MS Teams Action
        uses: FTsbrown/msteams-action@v1.0.1
        with:          
          TITLE: "Deploy to test starting"
          # Body of the message
          BODY: "<b>commit : </b>${{ github.sha }} <br> <b>Version : </b> ${{ env.VERSION_NO }} <br>"
          #MS_TEAMS_WEBHOOK: https://gablegrp.webhook.office.com/webhookb2/dd936596-4bd2-496c-8e78-b5bc1ba6fb8f@45be8033-beb7-4d4b-ab77-608ee11e6449/IncomingWebhook/18653518e0d344f5bd0d0492d54bbe77/89ed1696-cd46-4df0-b79f-ac4bc01308b1
          MS_TEAMS_WEBHOOK: ${{ env.MS_TEAM_URL }}
    
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ env.MS_TEAM_URL }}
          notification-summary: Your custom notification message 
          notification-color: 17a2b8
          timezone: America/Denver
