# This is a basic workflow to help you get started with Actions

name: test-notify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! 
          
      - name: MS Teams Action
          # You may pin to the exact commit or the version.
          # uses: FTsbrown/msteams-action@43cfa1a2ff5cf972b73616cec806792c88a85ff8
        uses: FTsbrown/msteams-action@v1.0.1
        with:
          # Title of the message
          TITLE: "GitHub Action Say Hi"
          # Body of the message
          BODY: "Hello World !<br>My Name<br><b>bird modify</b>"
          # If set, A MS Teams notification will be sent to this webhook
          MS_TEAMS_WEBHOOK: https://gablegrp.webhook.office.com/webhookb2/dd936596-4bd2-496c-8e78-b5bc1ba6fb8f@45be8033-beb7-4d4b-ab77-608ee11e6449/IncomingWebhook/18653518e0d344f5bd0d0492d54bbe77/89ed1696-cd46-4df0-b79f-ac4bc01308b1
