# This workflow will build and push a node.js application to an Azure Web App when there is a push to the master branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/azure/app-service/app-service-plan-manage#create-an-app-service-plan
#
# To configure this workflow:
#
# 1. For Linux apps, add an app setting called WEBSITE_WEBDEPLOY_USE_SCM and set it to true in your app **before downloading the file**.
#      For more instructions see: https://docs.microsoft.com/azure/app-service/configure-common#configure-app-settings
#
# 2. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples\
name: Post Deployment Testing
on:
  workflow_run:
    workflows: [deploy-to-testing]
    types:
      - completed
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: bird-webapp-demo-testing    # set this to your application's name  
  CONTAINER_REPO: 'birdmodify/birdtest-webapp'

jobs:   
  robot-testing:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      #needs: [build-container]
      environment: testing
      #url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - run: echo testing URL ${{ secrets.WEBAPP_URL }}       
            
      - name: Robot Framework
        # You may pin to the exact commit or the version.
        # uses: joonvena/robotframework-docker-action@3434822e049a0a5b2a02992e58c60a6831fa1189
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          # Shared memory that Docker container is allowed to use
          #allowed_shared_memory: # default is 1g
          # Browser to use
          #browser: # default is chrome     
          # Directory where Robot tests are located in the repository
          robot_tests_dir: ${{ github.workspace }}/robot_tests
          # Where will the report from test be saved
          robot_reports_dir: ${{ github.workspace }}/reports  
      
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
           name: reports
           path: ${{ github.workspace }}/reports
      
      
